# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tts.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttts.proto\x12\x06\x62ridge\x1a\x1bgoogle/protobuf/empty.proto\"\"\n\x04Text\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04part\x18\x02 \x01(\x05\"(\n\x06Speech\x12\x0e\n\x06speech\x18\x01 \x01(\x0c\x12\x0e\n\x06length\x18\x02 \x01(\x05\x32\xec\x01\n\x06\x42ridge\x12\x33\n\x0fGetSpeechStream\x12\x0c.bridge.Text\x1a\x0e.bridge.Speech\"\x00\x30\x01\x12+\n\tGetSpeech\x12\x0c.bridge.Text\x1a\x0e.bridge.Speech\"\x00\x12\x39\n\x13GetPartTextToSpeech\x12\x0c.bridge.Text\x1a\x0e.bridge.Speech\"\x00(\x01\x30\x01\x12\x45\n\x11\x44ownloadBarkModel\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tts_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TEXT']._serialized_start=50
  _globals['_TEXT']._serialized_end=84
  _globals['_SPEECH']._serialized_start=86
  _globals['_SPEECH']._serialized_end=126
  _globals['_BRIDGE']._serialized_start=129
  _globals['_BRIDGE']._serialized_end=365
# @@protoc_insertion_point(module_scope)
