// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: tts.proto

package bridge

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Text struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// text to be converted to speech.
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// Zero indexed part number of text while streaming Text (used for skipping purpose), put 0 i fnot streaming.
	Part int32 `protobuf:"varint,2,opt,name=part,proto3" json:"part,omitempty"`
}

func (x *Text) Reset() {
	*x = Text{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Text) ProtoMessage() {}

func (x *Text) ProtoReflect() protoreflect.Message {
	mi := &file_tts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Text.ProtoReflect.Descriptor instead.
func (*Text) Descriptor() ([]byte, []int) {
	return file_tts_proto_rawDescGZIP(), []int{0}
}

func (x *Text) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Text) GetPart() int32 {
	if x != nil {
		return x.Part
	}
	return 0
}

type Speech struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// speech in byte representation
	Speech []byte `protobuf:"bytes,1,opt,name=speech,proto3" json:"speech,omitempty"`
	// length of speech in seconds
	Length int32 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
}

func (x *Speech) Reset() {
	*x = Speech{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tts_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Speech) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Speech) ProtoMessage() {}

func (x *Speech) ProtoReflect() protoreflect.Message {
	mi := &file_tts_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Speech.ProtoReflect.Descriptor instead.
func (*Speech) Descriptor() ([]byte, []int) {
	return file_tts_proto_rawDescGZIP(), []int{1}
}

func (x *Speech) GetSpeech() []byte {
	if x != nil {
		return x.Speech
	}
	return nil
}

func (x *Speech) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

var File_tts_proto protoreflect.FileDescriptor

var file_tts_proto_rawDesc = []byte{
	0x0a, 0x09, 0x74, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x62, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x2e, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x72, 0x74,
	0x22, 0x38, 0x0a, 0x06, 0x53, 0x70, 0x65, 0x65, 0x63, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x70,
	0x65, 0x65, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x73, 0x70, 0x65, 0x65,
	0x63, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x32, 0xec, 0x01, 0x0a, 0x06, 0x42,
	0x72, 0x69, 0x64, 0x67, 0x65, 0x12, 0x33, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x70, 0x65, 0x65,
	0x63, 0x68, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x0c, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67,
	0x65, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x1a, 0x0e, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e,
	0x53, 0x70, 0x65, 0x65, 0x63, 0x68, 0x22, 0x00, 0x30, 0x01, 0x12, 0x2b, 0x0a, 0x09, 0x47, 0x65,
	0x74, 0x53, 0x70, 0x65, 0x65, 0x63, 0x68, 0x12, 0x0c, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65,
	0x2e, 0x54, 0x65, 0x78, 0x74, 0x1a, 0x0e, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x53,
	0x70, 0x65, 0x65, 0x63, 0x68, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x50, 0x61,
	0x72, 0x74, 0x54, 0x65, 0x78, 0x74, 0x54, 0x6f, 0x53, 0x70, 0x65, 0x65, 0x63, 0x68, 0x12, 0x0c,
	0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x1a, 0x0e, 0x2e, 0x62,
	0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x53, 0x70, 0x65, 0x65, 0x63, 0x68, 0x22, 0x00, 0x28, 0x01,
	0x30, 0x01, 0x12, 0x45, 0x0a, 0x11, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x61,
	0x72, 0x6b, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x14, 0x5a, 0x12, 0x65, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tts_proto_rawDescOnce sync.Once
	file_tts_proto_rawDescData = file_tts_proto_rawDesc
)

func file_tts_proto_rawDescGZIP() []byte {
	file_tts_proto_rawDescOnce.Do(func() {
		file_tts_proto_rawDescData = protoimpl.X.CompressGZIP(file_tts_proto_rawDescData)
	})
	return file_tts_proto_rawDescData
}

var file_tts_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tts_proto_goTypes = []interface{}{
	(*Text)(nil),          // 0: bridge.Text
	(*Speech)(nil),        // 1: bridge.Speech
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_tts_proto_depIdxs = []int32{
	0, // 0: bridge.Bridge.GetSpeechStream:input_type -> bridge.Text
	0, // 1: bridge.Bridge.GetSpeech:input_type -> bridge.Text
	0, // 2: bridge.Bridge.GetPartTextToSpeech:input_type -> bridge.Text
	2, // 3: bridge.Bridge.DownloadBarkModel:input_type -> google.protobuf.Empty
	1, // 4: bridge.Bridge.GetSpeechStream:output_type -> bridge.Speech
	1, // 5: bridge.Bridge.GetSpeech:output_type -> bridge.Speech
	1, // 6: bridge.Bridge.GetPartTextToSpeech:output_type -> bridge.Speech
	2, // 7: bridge.Bridge.DownloadBarkModel:output_type -> google.protobuf.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tts_proto_init() }
func file_tts_proto_init() {
	if File_tts_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Text); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tts_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Speech); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tts_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tts_proto_goTypes,
		DependencyIndexes: file_tts_proto_depIdxs,
		MessageInfos:      file_tts_proto_msgTypes,
	}.Build()
	File_tts_proto = out.File
	file_tts_proto_rawDesc = nil
	file_tts_proto_goTypes = nil
	file_tts_proto_depIdxs = nil
}
